### ISSUE TITLE
Issue with _this.notify

### ISSUE THREAD

**Issue by xavierverdejo** [joanroig/pccomponentes-outlet-bot#2]
Estoy teniendo un problema creo que con el bot de Telegram, os pongo aquí el código del error que me da:

TypeError: _this.notify is not a function
      at /home/xavier/Desktop/outlet/pccomponentes-outlet-bot/app.ts:64:10
      at Promise.resolve.then (/home/xavier/Desktop/outlet/pccomponentes-outlet-bot/node_modules/telegraf/composer.js:143:56)
      at process._tickCallback (internal/process/next_tick.js:68:7)

Failed to process updates. TypeError: _this.notify is not a function
    at /home/xavier/Desktop/outlet/pccomponentes-outlet-bot/app.ts:64:10
    at Promise.resolve.then (/home/xavier/Desktop/outlet/pccomponentes-outlet-bot/node_modules/telegraf/composer.js:143:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by xavierverdejo** [comment]
Solved creating new bot in Telegram.
